version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: 
      context: ./webshop-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/webshop
      - PORT=3001
      - CORS_ORIGIN=https://giannigiovanni.hu
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./gianni-app
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - VITE_API_URL=https://giannigiovanni.hu/api
    depends_on:
      - backend

volumes:
  mongodb_data: