version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: 
      context: ./webshop-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/webshop
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3002
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./gianni-app
      dockerfile: Dockerfile
    ports:
      - "3002:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

volumes:
  mongodb_data: